/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DVD;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class JavaDVDLib extends javax.swing.JFrame {

    /**
     * Creates new form JavaDVDLib
     */
    private static Connection con;
    private int delete_flag = 0;

    public JavaDVDLib() {
        initComponents();
        cboCode.setVisible(false);//Hide comboCode

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpSubTitles = new javax.swing.ButtonGroup();
        lblHeading = new javax.swing.JLabel();
        lblDVDCodeNo = new javax.swing.JLabel();
        txtCodeNo = new javax.swing.JTextField();
        txtTitle = new javax.swing.JTextField();
        lblLang = new javax.swing.JLabel();
        cboLang = new javax.swing.JComboBox<>();
        lblTitle = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblDollars = new javax.swing.JLabel();
        updPrice = new javax.swing.JSpinner();
        Subpanel = new javax.swing.JPanel();
        radYes = new javax.swing.JRadioButton();
        radNo = new javax.swing.JRadioButton();
        Controlpanel = new javax.swing.JPanel();
        btnAddNew = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        cboCode = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DVD Catalog");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeading.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading.setText("DVD CATALOG");
        lblHeading.setMaximumSize(new java.awt.Dimension(200, 25));
        lblHeading.setMinimumSize(new java.awt.Dimension(200, 25));
        getContentPane().add(lblHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 480, 50));

        lblDVDCodeNo.setText("DVD Code Number");
        lblDVDCodeNo.setOpaque(true);
        getContentPane().add(lblDVDCodeNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 118, 20));

        txtCodeNo.setEditable(false);
        txtCodeNo.setEditable(false);
        txtCodeNo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCodeNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeNoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCodeNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 150, 20));
        txtCodeNo.getAccessibleContext().setAccessibleDescription("");

        txtTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitleActionPerformed(evt);
            }
        });
        getContentPane().add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 272, -1));

        lblLang.setText("Language");
        getContentPane().add(lblLang, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 118, 20));

        cboLang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "Spanish", "French", "Chinese" }));
        cboLang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLangActionPerformed(evt);
            }
        });
        getContentPane().add(cboLang, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 175, -1));

        lblTitle.setText("DVD Title");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 120, 20));

        lblPrice.setText("Price");
        getContentPane().add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 118, 20));

        lblDollars.setText("Dollars");
        getContentPane().add(lblDollars, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 60, 20));

        updPrice.setModel(new javax.swing.SpinnerNumberModel(5, 5, 150, 1));
        getContentPane().add(updPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 78, -1));

        Subpanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Subtitles"));
        Subpanel.setLayout(new java.awt.GridLayout(1, 2));

        grpSubTitles.add(radYes);
        radYes.setSelected(true);
        radYes.setText("Yes");
        radYes.setToolTipText("");
        radYes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        radYes.setVerifyInputWhenFocusTarget(false);
        radYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radYesActionPerformed(evt);
            }
        });
        Subpanel.add(radYes);

        grpSubTitles.add(radNo);
        radNo.setText("No");
        radNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        radNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radNoActionPerformed(evt);
            }
        });
        Subpanel.add(radNo);

        getContentPane().add(Subpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 320, 80));

        Controlpanel.setPreferredSize(new java.awt.Dimension(100, 100));
        Controlpanel.setLayout(new java.awt.GridLayout(1, 5, 10, 0));

        btnAddNew.setText("Addnew");
        btnAddNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddNewMouseClicked(evt);
            }
        });
        Controlpanel.add(btnAddNew);

        btnUpdate.setText("Update");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        Controlpanel.add(btnUpdate);

        btnDelete.setText("Delete");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        Controlpanel.add(btnDelete);

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        Controlpanel.add(btnSave);

        btnCancel.setText("Cancel");
        btnCancel.setEnabled(false);
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        Controlpanel.add(btnCancel);

        getContentPane().add(Controlpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 400, 30));

        btnExit.setText("Exit");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 100, 30));

        cboCode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboCodeItemStateChanged(evt);
            }
        });
        cboCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCodeActionPerformed(evt);
            }
        });
        getContentPane().add(cboCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 150, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodeNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeNoActionPerformed

    private void txtTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitleActionPerformed

    private void radYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radYesActionPerformed

    private void radNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radNoActionPerformed

    private void cboLangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLangActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cboLangActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        // TODO add your handling code here
        try {
            //Check state of delete_fag
            if (delete_flag == 1) {

                Statement cmd = con.createStatement();
                int rs = cmd.executeUpdate("DELETE FROM DVD WHERE DVDCodeNo=" + cboCode.getSelectedItem());
                JOptionPane.showMessageDialog(this, "Đã xóa thành công!");
                cboCode.removeItem(cboCode.getSelectedItem());
                delete_flag = 0;
            } 
            else {
                //Check txtCodeNo in db, insert or update
                Statement check = con.createStatement();
                ResultSet checkrs = check.executeQuery("Select * from DVD where DVDCodeNo=" + txtCodeNo.getText());
                if (checkrs.next()) {
//                      checkrs.updateString("DVDTitle",txtTitle.getText().toString());
//                      checkrs.updateString("DVDLang",cboLang.getSelectedItem().toString());
//                      checkrs.updateString("DVDSubTitles",((Boolean) radYes.isSelected()).toString());
//                      checkrs.updateInt("DVDPrice",(int)updPrice.getValue());
                      
                    String query = "Update DVD set DVDTitle='" + txtTitle.getText()
                            + "', DVDLang='" + cboLang.getSelectedItem() + "', DVDSubTitles='"
                            + ((Boolean) radYes.isSelected()).toString() + "', DVDPrice=" + updPrice.getValue()
                            + " where DVDCodeNo=" + txtCodeNo.getText();
                    int checkreturn = check.executeUpdate(query);
                    JOptionPane.showMessageDialog(this, "Đã cập nhật thành công!");
                } else {
                    Statement cmd = con.createStatement();
                    String sql = "INSERT INTO DVD VALUES ("
                            + txtCodeNo.getText() + ",'"
                            + txtTitle.getText() + "','"
                            + cboLang.getSelectedItem() + "','"
                            + ((Boolean) radYes.isSelected()).toString() + "',"
                            + updPrice.getValue()
                            + ")";
                    int rs = cmd.executeUpdate(sql);
                    JOptionPane.showMessageDialog(this, "Đã thêm thành công!");

                }
            }
            //Thay doi trang thai cac nut nhu cu
            reset_BtnState();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi truy vấn");
        }
    }//GEN-LAST:event_btnSaveMouseClicked
    private void reset_BtnState() {
        //Thay doi trang thai cac nut nhu cu
        btnAddNew.setEnabled(true);
        btnDelete.setEnabled(true);
        btnUpdate.setEnabled(true);
        btnSave.setEnabled(false);
        btnCancel.setEnabled(false);
    }
    private void btnAddNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewMouseClicked
        // TODO add your handling code here:
        try {
            //Show DVDCodeNo textbox
            txtCodeNo.setVisible(true);
            cboCode.setVisible(false);
            //Reset button state
            reset_BtnState();
            //Query database to ++txtCodeNo
            Statement cmd = con.createStatement();
            ResultSet rs = cmd.executeQuery("SELECT MAX(DVDCodeNo) FROM DVD");
            if (rs.next()) {
                txtCodeNo.setText(rs.getInt(1) + 1 + "");
            } else {
                txtCodeNo.setText("0");
            }
            btnSave.setEnabled(true);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi truy vấn");
        }
    }//GEN-LAST:event_btnAddNewMouseClicked

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        try {
            con.close();
            System.exit(0);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        //TODO add your handling code here:
        try {
            //replace txtCode
            txtCodeNo.setVisible(false);
            cboCode.setVisible(true);
            //Disable update btn
            btnAddNew.setEnabled(false);
            btnUpdate.setEnabled(false);
            btnDelete.setEnabled(false);
            //allow save button and cancel button
            btnSave.setEnabled(true);
            btnCancel.setEnabled(true);
            Statement cmd = con.createStatement();
            ResultSet rs = cmd.executeQuery("SELECT DVDCodeNo FROM DVD");
            cboCode.removeAllItems();
            while (rs.next()) {
                cboCode.addItem(rs.getInt(1));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi truy vấn");
        }

    }//GEN-LAST:event_btnUpdateMouseClicked

    private void cboCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCodeActionPerformed

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
        try {
            delete_flag = 1;
            //replace txtCode
            txtCodeNo.setVisible(false);
            cboCode.setVisible(true);
            //Disable update btn
            btnAddNew.setEnabled(false);
            btnUpdate.setEnabled(false);
            btnDelete.setEnabled(false);
            //allow save button and cancel button
            btnSave.setEnabled(true);
            btnCancel.setEnabled(true);
            Statement cmd = con.createStatement();
            ResultSet rs = cmd.executeQuery("SELECT DVDCodeNo FROM DVD");
            cboCode.removeAllItems();
            while (rs.next()) {
                cboCode.addItem(rs.getInt(1));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi truy vấn");
        }

    }//GEN-LAST:event_btnDeleteMouseClicked

    private void cboCodeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboCodeItemStateChanged
        // TODO add your handling code here:
        try {
            Statement cmd = con.createStatement();
            ResultSet rs = cmd.executeQuery("SELECT * FROM DVD WHERE DVDCodeNo=" + cboCode.getSelectedItem());
            if (rs.next()) {
                txtCodeNo.setText(rs.getInt(1) + "");
                txtTitle.setText(rs.getString(2));
                cboLang.setSelectedItem(rs.getString(3));
                if (rs.getString(4).equals("true")) {
                    radYes.setSelected(true);
                } else {
                    radNo.setSelected(true);
                }
                updPrice.setValue(rs.getInt(5));
            }
            //
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi truy vấn");
        }
    }//GEN-LAST:event_cboCodeItemStateChanged

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
        //Reset state of button
        reset_BtnState();
        txtCodeNo.setVisible(true);
        cboCode.setVisible(false);
        //reset data field
        txtCodeNo.setText("");
        txtTitle.setText("");

    }//GEN-LAST:event_btnCancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaDVDLib.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaDVDLib.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaDVDLib.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaDVDLib.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display theform */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JavaDVDLib f = new JavaDVDLib();
                f.setVisible(true);
                try {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    String dbUrl = "jdbc:sqlserver://DESKTOP-BFM8AFS\\SQLEXPRESS:1433;databaseName=DVDLibrary;user=sa;password=sa2008";
                    con = DriverManager.getConnection(dbUrl);
                    Statement s = con.createStatement();
                    ResultSet rs = s.executeQuery("select * from DVD");
                    while (rs.next()) {
                        System.out.println("DVDCodeNo: " + rs.getInt(1) + " DVDTitle: " + rs.getString("DVDTitle") + " Language: " + rs.getString("DVDLang") + " DVDSuctitles: " + rs.getString("DVDSubTitles") + " DVDPrice: " + rs.getString("DVDPrice"));
                        System.out.println("------------------------------------------------------------------------------");
                    }

                } catch (Exception ex) {
                    ex.printStackTrace();
                }

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Controlpanel;
    private javax.swing.JPanel Subpanel;
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<Integer> cboCode;
    private javax.swing.JComboBox<String> cboLang;
    private javax.swing.ButtonGroup grpSubTitles;
    private javax.swing.JLabel lblDVDCodeNo;
    private javax.swing.JLabel lblDollars;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblLang;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton radNo;
    private javax.swing.JRadioButton radYes;
    private javax.swing.JTextField txtCodeNo;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JSpinner updPrice;
    // End of variables declaration//GEN-END:variables
}
