/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Buoi2;

/**
 *
 * @author Zevik
 */
public class StudentManager extends javax.swing.JFrame {

    /**
     * Creates new form Bai2
     */
    public StudentManager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnXeploai = new javax.swing.JButton();
        btnKetqua = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        txtMssv = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtNamsinh = new javax.swing.JTextField();
        txtQue = new javax.swing.JTextField();
        txtDiachi = new javax.swing.JTextField();
        txtDiem = new javax.swing.JTextField();
        txtXeploai = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblMssv = new javax.swing.JLabel();
        lblTen = new javax.swing.JLabel();
        lblNamsinh = new javax.swing.JLabel();
        lblQue = new javax.swing.JLabel();
        lblDiachi = new javax.swing.JLabel();
        lblDiem = new javax.swing.JLabel();
        lblXeploai = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lí sinh viên");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 440, -1));

        jLabel3.setText("Họ và tên");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 77, 72, -1));

        jLabel4.setText("Năm sinh");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 102, 72, -1));

        jLabel5.setText("Quê quán");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 127, 72, -1));

        jLabel6.setText("Địa chỉ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 152, 72, -1));

        jLabel7.setText("Điểm trung bình");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 180, 133, -1));

        jLabel8.setText("Xếp loại");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 177, 72, 19));

        btnXeploai.setText("Xếp loại");
        btnXeploai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXeploaiMouseClicked(evt);
            }
        });
        btnXeploai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXeploaiActionPerformed(evt);
            }
        });
        getContentPane().add(btnXeploai, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 30));

        btnKetqua.setText("Xem kết quả");
        btnKetqua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKetquaMouseClicked(evt);
            }
        });
        getContentPane().add(btnKetqua, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, 30));

        btnThoat.setText("Thoát");
        btnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThoatMouseClicked(evt);
            }
        });
        getContentPane().add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 70, 30));

        txtMssv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMssvActionPerformed(evt);
            }
        });
        getContentPane().add(txtMssv, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 48, 83, -1));

        txtTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenActionPerformed(evt);
            }
        });
        getContentPane().add(txtTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 77, 223, -1));
        getContentPane().add(txtNamsinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 102, 87, -1));
        getContentPane().add(txtQue, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 127, 87, -1));
        getContentPane().add(txtDiachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 152, 223, -1));

        txtDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiemActionPerformed(evt);
            }
        });
        getContentPane().add(txtDiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 177, 88, -1));
        getContentPane().add(txtXeploai, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 177, 55, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Mã số sinh viên");

        jLabel12.setText("Quê quán");

        jLabel11.setText("Năm sinh");

        jLabel13.setText("Địa chỉ");

        jLabel15.setText("Xếp loại");

        jLabel14.setText("Điểm trung bình");

        jLabel10.setText("Họ và tên");

        lblMssv.setText("None");

        lblTen.setText("None");

        lblNamsinh.setText("None");

        lblQue.setText("None");

        lblDiachi.setText("None");

        lblDiem.setText("None");

        lblXeploai.setText("None");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMssv, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTen, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNamsinh, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQue, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblXeploai, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMssv)
                        .addGap(8, 8, 8)
                        .addComponent(lblTen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNamsinh)
                        .addGap(12, 12, 12)
                        .addComponent(lblQue)
                        .addGap(12, 12, 12)
                        .addComponent(lblDiachi)
                        .addGap(15, 15, 15)
                        .addComponent(lblDiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(lblXeploai, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel12)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel13)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 420, 190));

        jLabel9.setText("Mã số sinh viên");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 51, 133, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXeploaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXeploaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXeploaiActionPerformed

    private void txtTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenActionPerformed

    private void txtDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtDiemActionPerformed

    private void btnXeploaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXeploaiMouseClicked
        // TODO add your handling code here:
        txtXeploai.setText("F");
        if (Double.parseDouble(txtDiem.getText())>=4){
            txtXeploai.setText("D");
        }
        if (Double.parseDouble(txtDiem.getText())>=5){
            txtXeploai.setText("D+");
        }
        if (Double.parseDouble(txtDiem.getText())>=5.5){
            txtXeploai.setText("C");
        }
        if (Double.parseDouble(txtDiem.getText())>=6.5){
            txtXeploai.setText("C+");
        }
        if (Double.parseDouble(txtDiem.getText())>=7){
            txtXeploai.setText("B");
        }
        if (Double.parseDouble(txtDiem.getText())>=8){
            txtXeploai.setText("B+");
        }
        if (Double.parseDouble(txtDiem.getText())>=9){
            txtXeploai.setText("A");
        }
       
    }//GEN-LAST:event_btnXeploaiMouseClicked

    private void btnKetquaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKetquaMouseClicked
        // TODO add your handling code here:
        lblMssv.setText(txtMssv.getText());
        lblTen.setText(txtTen.getText());
        lblNamsinh.setText(lblNamsinh.getText());
        lblQue.setText(txtQue.getText());
        lblDiachi.setText(txtDiachi.getText());
        lblDiem.setText(txtDiem.getText());
        lblXeploai.setText(txtXeploai.getText());
    }//GEN-LAST:event_btnKetquaMouseClicked

    private void btnThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnThoatMouseClicked

    private void txtMssvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMssvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMssvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKetqua;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXeploai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDiachi;
    private javax.swing.JLabel lblDiem;
    private javax.swing.JLabel lblMssv;
    private javax.swing.JLabel lblNamsinh;
    private javax.swing.JLabel lblQue;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblXeploai;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtDiem;
    private javax.swing.JTextField txtMssv;
    private javax.swing.JTextField txtNamsinh;
    private javax.swing.JTextField txtQue;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtXeploai;
    // End of variables declaration//GEN-END:variables
}
